default: &default
  adapter: postgresql
  username: postgres
  password: postgres
  host: localhost
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: sim_url_heroku_development

test:
  <<: *default
  database: sim_url_heroku_test

production:
  adapter: postgresql
  pool: 5
  encoding: utf8
  port: 5432
  database: <%= Rails.application.credentials[:heroku][:database] %>
  host: <%= Rails.application.credentials[:heroku][:host] %>
  username: <%= Rails.application.credentials[:heroku][:username] %>
  password: <%= Rails.application.credentials[:heroku][:password] %>

